# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "48c11f190fe107153899a7f870f79215"
name = "Fast Courier"
handle = "fc-dev"
application_url = "https://classroom-differences-excuse-ati.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "staging-fc.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_products,read_shipping,unauthenticated_read_checkouts,unauthenticated_write_checkouts,write_checkouts,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://classroom-differences-excuse-ati.trycloudflare.com/auth/callback",
  "https://classroom-differences-excuse-ati.trycloudflare.com/auth/shopify/callback",
  "https://classroom-differences-excuse-ati.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://fctest-api.fastcourier.com.au/api/wp/delete_merchant"
  customer_data_request_url = "https://fctest-api.fastcourier.com.au/api/wp/get_merchant"
  shop_deletion_url = "https://fctest-api.fastcourier.com.au/api/wp/delete_merchant"

[pos]
embedded = false
