# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "48c11f190fe107153899a7f870f79215"
name = "remix-app"
handle = "remix-app-139"
application_url = "https://belt-wooden-arthur-pace.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-development-fc-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_products,read_shipping,unauthenticated_read_checkouts,unauthenticated_write_checkouts,write_checkouts,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://belt-wooden-arthur-pace.trycloudflare.com/auth/callback",
  "https://belt-wooden-arthur-pace.trycloudflare.com/auth/shopify/callback",
  "https://belt-wooden-arthur-pace.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
