# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fba0237f7f8084edf2aa919f82b4a68d"
name = "Fast Courier"
handle = "fc-dev"
application_url = "https://wild-racks-gross-plus.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fc54-staging.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_checkouts,read_orders,read_products,read_shipping,unauthenticated_read_checkouts,unauthenticated_write_checkouts,write_checkouts,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://wild-racks-gross-plus.trycloudflare.com/auth/callback",
  "https://wild-racks-gross-plus.trycloudflare.com/auth/shopify/callback",
  "https://wild-racks-gross-plus.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://fctest-api.fastcourier.com.au/api/wp/delete_merchant"
  customer_data_request_url = "https://fctest-api.fastcourier.com.au/api/wp/get_merchant"
  shop_deletion_url = "https://fctest-api.fastcourier.com.au/api/wp/delete_merchant"

[pos]
embedded = false
